support for multilinestring layers
kartoza/stream_feature_extractor pull request #65
Opened 2021-10-13 13:10 UTC by vermeulendivan

2021-10-14 13:20 UTC, Samweli requested changes
@vermeulendivan I have requested small modifications to these changes, also it will be nice if you could add tests for the new `check_if_multipart` and `convert_multipart_to_singlepart` functions.

2021-10-14 13:20 UTC, Samweli commented on stream_utilities.py
> +    :type input_layer: QGISVectorLayer
```suggestion
    :type input_layer: QgsVectorLayer
```

2021-10-14 13:20 UTC, Samweli commented on stream_utilities.py
> +    :type input_layer: QGISVectorLayer
same as above

2021-10-14 13:20 UTC, Samweli commented on stream_utilities.py
> +    :rtype: QGISVectorLayer
same as above

2021-10-14 13:20 UTC, Samweli commented on stream_utilities.py
> +    input_crs = input_layer.sourceCrs()
```suggestion
    input_crs = input_layer.crs()
```

2021-10-14 21:21 UTC, vermeulendivan commented
@Samweli the two methods has been merged into one method now. made a change to the method which also now removes features with a null geometry. does this for both multilinestring and linestring files.

2021-10-15 09:38 UTC, Samweli approved these changes

2021-10-15 09:38 UTC, merged