Test-suite now works through github actions and tests has been done
kartoza/stream_feature_extractor pull request #86
Opened 2021-10-27 15:37 UTC by vermeulendivan

The test-suite can now be processed via github actions. The jobs includes QGIS 3.10, 3.12, 3.14, 3.16, 3.18, 3.20 and latest, and performs test on the plugin methods. Testing data has been updates. Contact information in comments has been updated.

2021-10-28 11:22 UTC, Samweli requested changes

2021-10-28 11:22 UTC, Samweli commented on .github/workflows/test_2.yml
> +          - release-3_20
@vermeulendivan can we also add QGIS-nightly and QGIS 3.22 images here.

2021-10-28 13:14 UTC, vermeulendivan commented on .github/workflows/test_2.yml
> +          - release-3_20
@Samweli qgis 3.22 added and doc commits removed

2021-10-29 10:37 UTC, Samweli approved these changes

2021-10-29 10:38 UTC, merged